language: node_js

node_js::
  - "8.11.1"

install:
  - npm install
  
before_script:
  - "make run-background" 
  - sleep 5

script: make test

notifications:
  webhooks:
    on_success: change  
    on_failure: always 
    on_start: never
